services:
  db:
    # image: postgres:10.10
    image: postgres:15.2
    container_name: CREPostgres
    environment:
      POSTGRES_PASSWORD: dbs
      # PGDATA: /var/lib/postgresql/data/pgdata      
    ports:
      - "5432:5432"
    # volumes:
      # - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dbsfdit/pgadmin:2023.ss
    container_name: dbsfdit-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5555:80"
    depends_on:
      - db
      
# volumes:
  # pgdata: