-- SQLite
/*
SELECT CR.CR_ID, CR.CR_RPY, PUB.PUB_PY
FROM CR 
JOIN PUB_CR ON (CR.CR_ID = PUB_CR.CR_ID)
JOIN PUB ON (PUB_CR.PUB_ID = PUB.PUB_ID)
*/


WITH PubYear AS (
    SELECT CR.CR_ID, PUB.PUB_PY, COUNT(*) AS N
    FROM CR 
    JOIN PUB_CR ON (CR.CR_ID = PUB_CR.CR_ID)
    JOIN PUB ON (PUB_CR.PUB_ID = PUB.PUB_ID)
    GROUP BY CR.CR_ID, PUB.PUB_PY
), 
PubYearComplete AS (
    SELECT C.CR_ID, S.PUB_PY, COALESCE (N, 0) AS N
    FROM (SELECT DISTINCT PUB_PY FROM PubYear) AS S
    JOIN (SELECT DISTINCT CR_ID FROM PubYear) AS C ON (1=1)
    LEFT OUTER JOIN PubYear ON (S.PUB_PY = PubYear.PUB_PY AND C.CR_ID = PubYear.CR_ID)
),
PubYearRange AS (
    SELECT P1.CR_ID, P1.PUB_PY, SUM (P2.N) AS N
    FROM PubYearComplete P1 
    JOIN PubYearComplete P2 ON (P1.CR_ID = P2.CR_ID AND ABS (P1.PUB_PY - P2.PUB_PY) <= 1)
    GROUP BY P1.CR_ID, P1.PUB_PY
)
, 
CRPercentiles AS (
    SELECT CR_ID, PUB_PY, N, 
    PERCENT_RANK()  
        OVER ( 
            PARTITION BY PUB_PY
            ORDER BY N ASC
        ) AS P
    FROM PubYearRange
)
SELECT *, (CASE WHEN P>=0.5 THEN 1 ELSE 0 END) AS P50,
    (CASE WHEN P>=0.75 THEN 1 ELSE 0 END) AS P75,
    (CASE WHEN P>=0.9 THEN 1 ELSE 0 END) AS P90
FROM CRPercentiles
ORDER BY CR_ID, PUB_PY


SELECT CR_ID, 
    SUM (CASE WHEN P>=0.5 THEN 1 ELSE 0 END) AS P50,
    SUM (CASE WHEN P>=0.75 THEN 1 ELSE 0 END) AS P75,
    SUM (CASE WHEN P>=0.9 THEN 1 ELSE 0 END) AS P90
FROM CRPercentiles
GROUP BY CR_ID




SELECT *, (CASE WHEN P>=0.5 THEN 1 ELSE 0 END) AS P50,
    (CASE WHEN P>=0.75 THEN 1 ELSE 0 END) AS P75,
    (CASE WHEN P>=0.9 THEN 1 ELSE 0 END) AS P90
FROM CRPercentiles
ORDER BY CR_ID, PUB_PY


SELECT CR_ID, 
    SUM (CASE WHEN P>=0.5 THEN 1 ELSE 0 END) AS P50,
    SUM (CASE WHEN P>=0.75 THEN 1 ELSE 0 END) AS P75,
    SUM (CASE WHEN P>=0.9 THEN 1 ELSE 0 END) AS P90
FROM CRPercentiles
GROUP BY CR_ID



SELECT *
FROM CRPercentiles
ORDER BY CR_ID, PUB_PY
,
    


SELECT CR_ID, COUNT(DISTINCT PUB_PY)
FROM PubYear
GROUP BY CR_ID
