services:
  db:
    image: postgres:15.2
    container_name: cre-postgres
    environment:
      POSTGRES_USER: cre
      POSTGRES_PASSWORD: cre
      POSTGRES_DB: crexplorer    
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:6.14
    container_name: cre-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5555:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json    
    depends_on:
      - db
      
